### ISSUE TITLE
building cql-parsetree results in error

### ISSUE THREAD

**Issue by revans2023** [cqframework/clinical_quality_language#1107]
I am on a Windows machine with Java JDK 19 and Gradle 7.6 (in order to use this version of Gradle I had to modify "gradle-wrapper.properties" to have - distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip

I cannot build "cql-parsetree" as the following error occurs:
clinical_quality_language\Src\java> .\gradlew :tools:cql-parsetree:run
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :tools:cql-parsetree:run FAILED
Exception in thread "main" java.lang.NoClassDefFoundError: org/abego/treelayout/TreeForTreeLayout
        at org.antlr.v4.gui.Trees.inspect(Trees.java:25)
        at org.antlr.v4.gui.Trees.inspect(Trees.java:32)
        at org.cqframework.cql.tools.parsetree.Main.main(Main.java:35)
Caused by: java.lang.ClassNotFoundException: org.abego.treelayout.TreeForTreeLayout
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 3 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tools:cql-parsetree:run'.

**Comment by revans2023** [comment]
I found the issue as the "build.gradle" file in the "Src/Java" folder has a bug in it as the "org.abego.treelayout" is not part of ANTLR4 so when the exclude is remove the "cql-parsetree" will again be working.

**ORIGINAL**:
dependencies {
    implementation project(':cql')
    implementation (group: "org.antlr", name: "antlr4", version: "4.10.1") {
        // antlr 4.5 includes these classes directly
        exclude(group: "org.abego.treelayout", module: "org.abego.treelayout.core")
    }
}

**WORKS**:
dependencies {
    implementation project(':cql')
    implementation (group: "org.antlr", name: "antlr4", version: "4.10.1")
}

**Comment by JPercival** [comment]
Resolved on master
