### ISSUE TITLE
 java.lang.OutOfMemoryError when tracking many (~8k) evaluated resources

### ISSUE THREAD

**Issue by JPercival** [cqframework/clinical_quality_language#1116]
The cql-engine throws an exception when tracking lots of evaluated resources even when allocated ~20Gb of memory (via `-Xmx20g`)

```
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
        at java.base/java.util.ArrayList.toArray(ArrayList.java:401)
        at java.base/java.util.ArrayList.addAll(ArrayList.java:702)
        at org.opencds.cqf.cql.engine.execution.Context.popEvaluatedResourceStack(Context.java:113)
        at org.opencds.cqf.cql.engine.elm.execution.ExpressionDefEvaluator.internalEvaluate(ExpressionDefEvaluator.java:33)
        at org.opencds.cqf.cql.engine.elm.execution.Executable.evaluate(Executable.java:14)
```

**Comment by JPercival** [comment]
Resolved by #1122
