### ISSUE TITLE
Execution Engine: Cannot Sort By Function

### ISSUE THREAD

**Issue by cmoesel** [cqframework/clinical_quality_language#125]
The execution engine fails when attempting to sort queries using a function.  For example:
```
define function square (a System.Integer) :
  a * a

define SortBySquareFunction:
  ({1, 3, 2, 5, 4}) N sort by square(N)
```

When attempting to execute `SortBySquareFunction`, the execution engine throws an error like the following:
```
TypeError: Cannot read property 'parameters' of undefined
      at FunctionRef.module.exports.FunctionRef.FunctionRef.exec (lib/elm/reusable.js:87:38)
      at ByExpression.module.exports.ByExpression.ByExpression.exec (lib/elm/query.js:135:31)
      at lib/elm/query.js:191:28
      at Array.sort (native)
      at SortClause.module.exports.SortClause.SortClause.sort (lib/elm/query.js:184:23)
      at Query.module.exports.Query.Query.exec (lib/elm/query.js:301:14)
      at Context.<anonymous> (test/elm/reusable/test.coffee:52:27)
```

_(NOTE: I previously thought this was an error related to using included libraries, but that is not the case, so I have edited the issue to reflect the real problem.)_

**Comment by cmoesel** [comment]
BTW -- I'm looking into this, hoping to fix ASAP.

**Comment by cmoesel** [comment]
The example above is actually invalid since it refers to the alias (which is out of scope at that point). 
 Instead of referring to the alias, the variable `$this` should be used instead.  For example:
```
define function square (a System.Integer) :
  a * a

define SortBySquareFunction:
  ({1, 3, 2, 5, 4}) N sort by square($this)
```

See #127.
