### ISSUE TITLE
Age functions fail when a patient has a null or undefined birthDate

### ISSUE THREAD

**Issue by jgibson** [cqframework/clinical_quality_language#192]
If you define a patient with no `birthDate` and execute the following CQL:

    define "MissingAge": AgeInYears() is null
Then it will fail with a stack trace:
```
TypeError: Cannot read property 'toJSDate' of null
      at CalculateAge.module.exports.CalculateAge.CalculateAge.exec (node_modules/cql-execution/lib/elm/clinical.js:262:33)
      at GreaterOrEqual.module.exports.Expression.Expression.execArgs (node_modules/cql-execution/lib/elm/expression.js:36:30)
      at GreaterOrEqual.module.exports.GreaterOrEqual.GreaterOrEqual.exec (node_modules/cql-execution/lib/elm/comparison.js:77:19)
      at And.module.exports.Expression.Expression.execArgs (node_modules/cql-execution/lib/elm/expression.js:36:30)
      at And.module.exports.And.And.exec (node_modules/cql-execution/lib/elm/logical.js:19:64)
      at ExpressionDef.module.exports.ExpressionDef.ExpressionDef.exec (node_modules/cql-execution/lib/elm/reusable.js:23:53)
      at Executor.module.exports.Executor.Executor.exec_patient_context (node_modules/cql-execution/lib/runtime/executor.js:62:71)
      at Executor.module.exports.Executor.Executor.exec (node_modules/cql-execution/lib/runtime/executor.js:41:24)
      at Context.testFunc (test/loadTestCases/index.js:138:36)
```

This is in version `cql-execution-0.0.6-011abcd0c243d017e47ed82e2c74bd0acc46841f`. I haven't test the `Age*At` functions, but they may have the same problem.

Fortunately this bug may already be fixed on the cql4bonnie branch by the changes to  `Src/coffeescript/cql-execution/src/elm/clinical.coffee` in 0ba67baebf3165f0d0fc2cbd2826d231c9593e9c.

**Comment by jgibson** [comment]
I can confirm that this bug is fixed on the cql4bonnie branch.

**Comment by brynrhodes** [comment]
This issue was moved to cqframework/cql-execution#45
