### ISSUE TITLE
Invoking Coalesce with a single argument yields an internal error

### ISSUE THREAD

**Issue by jgibson** [cqframework/clinical_quality_language#198]
If you accidentally call Coalesce with a single argument then it will crash the executor. Ideally it should provide a useful error message. For example, running this:

    Last(ObsList O sort by Coalesce(O.valueQuantity.value))

will cause this error:

    TypeError: Cannot read property 'parameters' of undefined
      at FunctionRef.module.exports.FunctionRef.FunctionRef.exec (node_modules/cql-execution/lib/elm/reusable.js:87:38)
      at FunctionRef.module.exports.Expression.Expression.execute (node_modules/cql-execution/lib/elm/expression.js:34:21)
      at ByExpression.module.exports.ByExpression.ByExpression.exec (node_modules/cql-execution/lib/elm/query.js:136:31)
      at node_modules/cql-execution/lib/elm/query.js:192:28
      at Array.sort (native)
      at SortClause.module.exports.SortClause.SortClause.sort (node_modules/cql-execution/lib/elm/query.js:185:23)
      at Query.module.exports.Query.Query.exec (node_modules/cql-execution/lib/elm/query.js:302:14)
      at Last.module.exports.Last.Last.exec (node_modules/cql-execution/lib/elm/list.js:315:25)
      at Last.module.exports.Expression.Expression.execute (node_modules/cql-execution/lib/elm/expression.js:34:21)
      at FunctionRef.module.exports.FunctionRef.FunctionRef.exec (node_modules/cql-execution/lib/elm/reusable.js:95:37)
      at FunctionRef.module.exports.Expression.Expression.execute (node_modules/cql-execution/lib/elm/expression.js:34:21)
      at ExpressionDef.module.exports.ExpressionDef.ExpressionDef.exec (node_modules/cql-execution/lib/elm/reusable.js:23:53)
      at ExpressionDef.module.exports.Expression.Expression.execute (node_modules/cql-execution/lib/elm/expression.js:34:21)
      at Executor.module.exports.Executor.Executor.exec_patient_context (node_modules/cql-execution/lib/runtime/executor.js:62:58)
      at Executor.module.exports.Executor.Executor.exec (node_modules/cql-execution/lib/runtime/executor.js:41:24)

This stacktrace is from the cql4bonnie branch, commit f0841f35.

**Comment by cmoesel** [comment]
Thanks for reporting this...  we'll take a look and see what's possible.  At the least, I expect we should be able to return a more useful error message.

**Comment by brynrhodes** [comment]
This issue was moved to cqframework/cql-execution#44
