### ISSUE TITLE
java-quickstart Gradle wrapper appears to be broken

### ISSUE THREAD

**Issue by kjmahalingam** [cqframework/clinical_quality_language#525]
When trying to run the `.gradlew build` command in the java-quickstart instructions, this error occurs:

```
MM232274-PC:java-quickstart kmahalingam$ ./gradlew build
Downloading http://services.gradle.org/distributions/gradle-2.0-bin.zip

Exception in thread "main" java.io.IOException: Server returned HTTP response code: 403 for URL: http://services.gradle.org/distributions/gradle-2.0-bin.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:56)
	at org.gradle.wrapper.Download.download(Download.java:42)
	at org.gradle.wrapper.Install$1.call(Install.java:57)
	at org.gradle.wrapper.Install$1.call(Install.java:44)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:44)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:126)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
```

**Comment by brynrhodes** [comment]
Addressed in 1.4.9 release
