### ISSUE TITLE
unable to cql-to-elm in json format

### ISSUE THREAD

**Issue by ErichBSchulz** [cqframework/clinical_quality_language#56]
following instruction here https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/README.md

the -f option breaks it:

root@a4257a35358c:/usr/src/myapp/Src/java# ./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --output temp.json -f=json

```
Exception in thread "main" joptsimple.OptionArgumentConversionException: Cannot parse argument 'json' of option ['format']
	at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:94)
	at joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:276)
	at joptsimple.OptionSet.valuesOf(OptionSet.java:223)
	at joptsimple.OptionSet.valueOf(OptionSet.java:172)
	at joptsimple.AbstractOptionSpec.value(AbstractOptionSpec.java:67)
	at org.cqframework.cql.cql2elm.CqlTranslator.main(CqlTranslator.java:234)
Caused by: joptsimple.internal.ReflectionException: java.lang.IllegalArgumentException: No enum constant org.cqframework.cql.cql2elm.Cq
lTranslator.Format.json
	at joptsimple.internal.Reflection.reflectionException(Reflection.java:140)
	at joptsimple.internal.Reflection.invoke(Reflection.java:122)
	at joptsimple.internal.MethodInvokingValueConverter.convert(MethodInvokingValueConverter.java:48)
	at joptsimple.internal.Reflection.convertWith(Reflection.java:128)
	at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:91)
	... 5 more
Caused by: java.lang.IllegalArgumentException: No enum constant org.cqframework.cql.cql2elm.CqlTranslator.Format.json
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.cqframework.cql.cql2elm.CqlTranslator$Format.valueOf(CqlTranslator.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at joptsimple.internal.Reflection.invoke(Reflection.java:119)
	... 8 more
```

this works (but makes xml):

    root@a4257a35358c:/usr/src/myapp/Src/java# ./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --output temp.json

**Comment by ErichBSchulz** [comment]
all of these died too: 

```./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql -s -f json
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql -f json
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql 
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --format json
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --format "json"
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --format="json"
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --format=json
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --output temp.txt --format=json
./cql-to-elm/build/install/cql-to-elm/bin/cql-to-elm --input ../../Examples/ChlamydiaScreening_CQM.cql --output temp.json -f=json
```

**Comment by cmoesel** [comment]
Well... that's embarassing.

Turns out it should be `JSON`, not `json`.  I've fixed it in the readme.  Once you confirm you've got it working, I'll close the issue.

**Comment by ErichBSchulz** [comment]
yes - i just figured that out reading the code! 

and I see you've just fixed the readme! thanks
