### ISSUE TITLE
CQL-to-ELM Translator - STDOUT Option

### ISSUE THREAD

**Issue by joelmontavon** [cqframework/clinical_quality_language#731]
I'm trying to use the --stdout option for the CQL-to-ELM Translator but am getting an error that stdout is not a recognized option.

D:\projects\cql\clinical_quality_language\Src\java>"C:\Program Files\Java\jdk-11.0.10\bin\java.exe" -classpath "D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\cql-to-elm-1.5.4.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\elm-1.5.4.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\model-1.5.4.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\quick-1.5.4.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\qdm-1.5.4.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jaxb2-basics-0.12.0.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jackson-module-jaxb-annotations-2.10.1.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jakarta.xml.bind-api-2.3.3.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jackson-databind-2.10.1.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jackson-annotations-2.10.1.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\org.eclipse.persistence.moxy-2.7.7.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\cql-1.5.4.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jopt-simple-4.7.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\ucum-1.0.3.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jaxb2-basics-tools-0.12.0.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jaxb2-basics-runtime-0.12.0.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\javaparser-1.0.11.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jakarta.activation-api-1.2.2.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\org.eclipse.persistence.core-2.7.7.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\antlr4-runtime-4.9.1.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\commons-lang3-3.10.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\xpp3-1.1.4c.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\xpp3_xpath-1.1.4c.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jackson-core-2.10.1.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\jcl-over-slf4j-1.7.7.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\slf4j-api-1.7.7.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\commons-beanutils-1.9.3.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\org.eclipse.persistence.asm-2.7.7.jar;D:\projects\cql\clinical_quality_language\Src\java\cql-to-elm\build\install\cql-to-elm\lib\commons-collections-3.2.2.jar" org.cqframework.cql.cql2elm.CqlTranslator --input D:\projects\cql\cql-execution\examples\node\test.cql --stdout
Exception in thread "main" joptsimple.UnrecognizedOptionException: 'stdout' is not a recognized option
        at joptsimple.OptionException.unrecognizedOption(OptionException.java:89)
        at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:447)
        at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
        at joptsimple.OptionParser.parse(OptionParser.java:379)
        at org.cqframework.cql.cql2elm.CqlTranslator.main(CqlTranslator.java:768)

**Comment by csandersdev** [comment]
The [CqlTranslator ](https://github.com/cqframework/clinical_quality_language/blob/f6e4542e7bfa57db776ae61570444d5a13239df6/Src/java/cql-to-elm/src/main/java/org/cqframework/cql/cql2elm/CqlTranslator.java#L753) does not currently define a `stdout` option in is options parser definition. You can either use the `output` option to define a target file or folder or, if not present, the translator will automatically determine a target relative to the CQL source that is being translated.

I do see that the [Overview.MD](https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/cql-to-elm/OVERVIEW.md) mentions it, so maybe this is a documentation issue? It would be pretty trivial to add support if there was a need for this feature.

**Comment by joelmontavon** [comment]
I am looking at the documentation here: https://github.com/cqframework/clinical_quality_language/blob/f6e4542e7bfa57db776ae61570444d5a13239df6/Src/java/cql-to-elm/OVERVIEW.md.

**Comment by brynrhodes** [comment]
@joelmontavon , what do you need the stdout option to do? Is it just to route the message output or are you trying to capture the actual translated ELM output?

**Comment by joelmontavon** [comment]
I am trying to capture the message output. There are probably other ways to accomplish this and have started a thread in FHIR chat.
